public class HeavyCoupling {
  void run() {
    new A().a();
    new B().b();
    new C().c();
    new D().d();
    new E().e();
    new F().f();
    new G().g();
    new H().h();
    new I().i();
    new J().j();
    new K().k();
    new L().l();
    new M().m();
    new N().n();
    new O().o();
    new P().p();
    new Q().q();
    new R().r();
    new S().s();
    new T().t();
    new U().u();
  }
}
