public class ManyFields {
  private String f1;
  private String f2;
  private String f3;
  private String f4;
  private String f5;
  private String f6;
  private String f7;
  private String f8;
  private String f9;
  private String f10;
  private Integer f11;
  private Integer f12;
  private Integer f13;
  private Integer f14;
  private Integer f15;
  private Integer f16;
  private Integer f17;
  private Integer f18;
  private Integer f19;
  private Integer f20;
  private Boolean f21;
}
